# Site settings
title: Emacs Blog
email: ben@s10r.com
description: >
  Describing my current use of Emacs for programming (mostly Ruby,) and
  chronicling attempts to expand my use.
baseurl: ""
url: "http://emacs.s10r.com"
twitter_username: bschmeck
github_username:  bschmeck

# Build settings
markdown: kramdown
